version: "3"
services:
  nginx:
    ports:
      - "80:80"
  node-app:
    build:
      context: .
      args:
        NODE_ENV: "production"
    volumes:
      - /app/node_modules
    environment:
      - PORT=3435
      - NODE_ENV=production
      - MONGO_PORT=27017
      - MONGO_IP=mongo
      - MONGO_USER=user
      - MONGO_PASSWORD=password
      - SESSION_SECRET=keyboard_cat
    command: npm run start
