version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3435:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app
    networks:
      - api-server_default
      - default

  node-app:
    build: .
    image: theallegrarr/node-app
    ports:
      - "3435"
    environment:
      - PORT=3435
      - REDIS_URL=redis
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db:

networks:
  api-server_default:
    external: true
